approve_by_comment: true
approve_regex: ^(Ship it|ship it|LGTM)
reject_regex: ^(Rejected|rejected)
reset_on_push: false
reviewers:
  members:
  - lhaiesp
  - lisamarth
  - pdu-mn1
  - raghupc
  - srinipunuru
  - tlazaro
  name: default
  required: 2
